spring.application.name=MUKJA

# JSP Ã¬ÂÂ¤Ã¬Â Â
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle Ã¬ÂÂ¤Ã¬Â Â
spring.datasource.url=jdbc:oracle:thin:@//192.168.10.29:1521/XEPDB1
spring.datasource.username=magazine
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# MyBatis Ã¬ÂÂ¤Ã¬Â Â
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml

# Ã­ÂÂÃ¬ÂÂ¼Ã¬ÂÂÃ«Â¡ÂÃ«ÂÂ Ã¬ÂÂ¤Ã¬Â Â
# Ã¬ÂµÂÃ«ÂÂ Ã­ÂÂÃ¬ÂÂ¼ Ã­ÂÂ¬ÃªÂ¸Â° Ã¬ÂÂ¤Ã¬Â Â (ÃªÂ¸Â°Ã«Â³Â¸ÃªÂ°Â : 1MB)
spring.servlet.multipart.max-file-size = 10MB
# Ã¬ÂµÂÃ«ÂÂ Ã¬ÂÂÃ¬Â²Â­ Ã­ÂÂ¬ÃªÂ¸Â° Ã¬ÂÂ¤Ã¬Â Â (ÃªÂ¸Â°Ã«Â³Â¸ÃªÂ°Â : 1MB)
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ckehdlf1@gmail.com
spring.mail.password=jyit pbxl ceid onhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# 로그인 세션 유지시간
server.servlet.session.timeout=60m