spring.application.name=MUKJA

# JSP ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ
spring.datasource.url=jdbc:oracle:thin:@//192.168.10.29:1521/XEPDB1
spring.datasource.username=magazine
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# MyBatis ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml

# ÃÂ­ÃÂÃÂÃÂ¬ÃÂÃÂ¼ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¡ÃÂÃÂ«ÃÂÃÂ ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ
# ÃÂ¬ÃÂµÃÂÃÂ«ÃÂÃÂ ÃÂ­ÃÂÃÂÃÂ¬ÃÂÃÂ¼ ÃÂ­ÃÂÃÂ¬ÃÂªÃÂ¸ÃÂ° ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ (ÃÂªÃÂ¸ÃÂ°ÃÂ«ÃÂ³ÃÂ¸ÃÂªÃÂ°ÃÂ : 1MB)
spring.servlet.multipart.max-file-size = 10MB
# ÃÂ¬ÃÂµÃÂÃÂ«ÃÂÃÂ ÃÂ¬ÃÂÃÂÃÂ¬ÃÂ²ÃÂ­ ÃÂ­ÃÂÃÂ¬ÃÂªÃÂ¸ÃÂ° ÃÂ¬ÃÂÃÂ¤ÃÂ¬ÃÂ ÃÂ (ÃÂªÃÂ¸ÃÂ°ÃÂ«ÃÂ³ÃÂ¸ÃÂªÃÂ°ÃÂ : 1MB)
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ckehdlf1@gmail.com
spring.mail.password=jyit pbxl ceid onhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ë¡ê·¸ì¸ ì¸ì ì ì§ìê°
server.servlet.session.timeout=60m

#엘라스틱서치 접속 ip
spring.elasticsearch.uris=http://192.168.10.49:9200