spring.application.name=MUKJA

# JSP ì¤ì 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle ì¤ì 
spring.datasource.url=jdbc:oracle:thin:@//192.168.10.29:1521/XEPDB1
spring.datasource.username=magazine
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# MyBatis ì¤ì 
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml

# íì¼ìë¡ë ì¤ì 
# ìµë íì¼ í¬ê¸° ì¤ì  (ê¸°ë³¸ê° : 1MB)
spring.servlet.multipart.max-file-size = 10MB
# ìµë ìì²­ í¬ê¸° ì¤ì  (ê¸°ë³¸ê° : 1MB)
spring.servlet.multipart.max-request-size = 10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ckehdlf1@gmail.com
spring.mail.password=jyit pbxl ceid onhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
